---
- name: Daily Operations Playbook
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks: 
  - name: Update apt-cache 
    apt: update_cache=yes
  - name: Updating Packages 
    apt:  upgrade=dist force_apt_get=yes
  - name: Daily Reboot
    reboot: 
    when: ansible_os_family == "Debian"
    
  
